### ISSUE TITLE
tsdb/tsi1 tests failing in CI

### ISSUE THREAD

**Issue by wolffcm** [influxdata/platform#1832] opened 2018-12-11 16:35 UTC
After I merged just now, CI started failed on master in the `make go-test-race` step.  After I reran, it passed.

https://circleci.com/gh/influxdata/platform/9163?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

The failure seems to be happening here:
```
=== RUN   TestIndex_MeasurementCardinalityStats
=== RUN   TestIndex_MeasurementCardinalityStats/Empty
=== RUN   TestIndex_MeasurementCardinalityStats/Simple
=== RUN   TestIndex_MeasurementCardinalityStats/SimpleWithDelete
=== RUN   TestIndex_MeasurementCardinalityStats/Large
FAIL	github.com/influxdata/platform/tsdb/tsi1	97.896s
```
This doesn't seem to be related to my change though, since it also failed on a feature branch similarly:
https://circleci.com/gh/influxdata/platform/9074?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mark-rushakoff** [comment] 2018-12-11 16:47
My guess at this point would be that an individual test's main goroutine completed successfully, then printed `PASS`, and then a separate goroutine for that test called t.Error, which caused that test to "retroactively" fail and caused the suite to fail.

**Comment by mark-rushakoff** [comment] 2018-12-11 19:47
Happened again at https://circleci.com/gh/influxdata/platform/9179. I'm going to take a couple minutes to try and repro locally.

**Comment by mark-rushakoff** [comment] 2018-12-11 21:42
I ran `while go test -count=1 ./tsdb/tsi1/ -v -race -p=8; do date; done` for about 30 minutes and wasn't able to reproduce the error on my machine.

I was wrong about the separate goroutine failing the test after it completed; when that happens, there's a `panic: Fail in goroutine after TestFoo has completed`. So at this point, I'm really unsure what's going on with this failure.

**Comment by mark-rushakoff** [comment] 2018-12-12 16:07
Another failure: https://circleci.com/gh/influxdata/platform/9341

Thinking about using `go test -json` in CI to see if that somehow captures more failure detail.

It's really difficult to find that failure in the logs, because it doesn't match `FAIL:`; when you just search for "fail" without the colon, there's 132 case-insensitive matches in the link above, from other test names and test log output.

**Comment by mark-rushakoff** [comment] 2018-12-13 16:42
The presumed fix hasn't been merged yet, but it looks like https://circleci.com/gh/influxdata/platform/9469 and https://circleci.com/gh/influxdata/platform/9430 from yesterday both failed with the symptoms of this issue - and those were just merges to master; I didn't look at individual PRs that may have needed retries.

**Comment by mark-rushakoff** [comment] 2018-12-13 16:46
Assuming #1871 closes this, but let's keep an eye out for that failure in case it still happens.

**Closed by mark-rushakoff** 2018-12-13 16:46 UTC
