### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#261] opened 2018-07-03 21:50 UTC
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#296  

There are three different contexts in which errors can arise when executing a query:

1. With just the text of the query
2. With text of the query and the data schema
3. With the text, schema and values of the data.

How should we handle errors are each of these layers?

The first layer is straightforward, when ever a user submits an invalid query text reject it and return an error. 

The second is also clear, since no data will be able to be processed, kill the query and return the error.

The third has at least two ways it could be handled. Log the error and increase a counter and move on. Alternatively kill the entire query.

Are there other methods that apply to the third layer? If not then is seems like a simple global toggle for the query would be sufficient to allow users to choose their desired behavior.

**Comment by nathanielc** [comment] 2018-07-17 23:14
This is a duplicate of #341

**Closed by nathanielc** 2018-07-17 23:14 UTC
Labels: area/query, area/query/needsreview
