### ISSUE TITLE
/v1/bucket endpoint should support different time durations for retentionPeriod 

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#144] opened 2018-06-15 17:32 UTC
v1/bucket endpoint for creating the buckets currently only accepts pure integers, i.e. 3, 4, etc, which defaults to `ns`. It should be able to handle other time durations as well, such as seconds, minutes, hours, weeks.

**Comment by goller** [comment] 2018-09-17 13:04
Duplicate of #796

**Closed by goller** 2018-09-17 13:04 UTC
Labels: bug

**Comment by gshif** [comment] 2018-09-27 00:28
https://github.com/influxdata/platform/pull/864
